version: '2.3'


services:

# Elasticpot service
  elasticpot:
    # build: .
    container_name: elasticpot
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    network_mode: "host"
    ports:
     - "9200:9200"
    image: "dtagdevsec/elasticpot:24.04"
    read_only: true
    volumes:
     - $PWD/data/elasticpot/log:/opt/elasticpot/log
