version: '2.3'

networks:
  cowrie_local:

services:

# Cowrie service
  cowrie:
    # build: .
    container_name: cowrie
    restart: always
    tmpfs:
     - /tmp/cowrie:uid=2000,gid=2000
     - /tmp/cowrie/data:uid=2000,gid=2000
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - cowrie_local
    ports:
     - "222:22"
     - "223:23"
    image: "dtagdevsec/cowrie:24.04"
    read_only: true
    volumes:
     - $PWD/data/cowrie/downloads:/home/cowrie/cowrie/dl
     - $PWD/data/cowrie/keys:/home/cowrie/cowrie/etc
     - $PWD/data/cowrie/log:/home/cowrie/cowrie/log
     - $PWD/data/cowrie/log/tty:/home/cowrie/cowrie/log/tty
